output.strings = {
  "16_years_old_legal_text": "Continue if you are at least 16 years old and agree to the Terms & Conditions & Privacy Policy",
  "Mark ${applicationName} recipe as cooked": "Mark ${applicationName} recipe as cooked",
  "Next ${applicationName} step": "Next ${applicationName} step",
  "Not_Subscribed_After_Onboarding_Banner_Button": "SUBSCRIBE TO MEAL PLAN",
  "Not_Subscribed_After_Onboarding_Banner_Text": "Subscribe now to discover your individual meal plans.",
  "Not_Subscribed_After_Onboarding_Banner_Title": "Your preferences are saved",
  "Plan": "Meal plan",
  "Previous ${applicationName} step": "Previous ${applicationName} step",
  "Recipe.Type.Beef": "Beef",
  "Recipe.Type.Fish": "Fish",
  "Recipe.Type.Game": "Game",
  "Recipe.Type.Lamb": "Lamb",
  "Recipe.Type.Pork": "Pork",
  "Recipe.Type.Poultry": "Poultry",
  "Recipe.Type.Seafood": "Seafood",
  "Recipe.Type.Vegan": "Vegan",
  "Recipe.Type.Veggie": "Vegetarian",
  "account_ahoilabel": "Ahoy, Kptn!",
  "account_desclabel": "Create a free account and get unlimited recipe space.",
  "account_skipbutton": "Maybe later",
  "account_termslabel": "By creating an account, you accept KptnCook's",
  "account_title": "Come on board!",
  "action_discover": "Discover",
  "action_plan": "Plan",
  "add_recipe_to_mealplan": "Add to meal plan",
  "addingredient_deleteitemquestion": "Do you want to delete this article?",
  "addingredient_productaddedtext": "Product added",
  "addingredient_productchangedtext": "Product changed",
  "addingredient_recipetitle": "Personal items",
  "addingredient_title_placeholder": "What do you need?",
  "adjust_ingredients": "Adjust ingredient",
  "app_store": "App Store",
  "appliance_recommendation_section_title": "Works great with",
  "aus_dem_plan_entfernen": "Remove from Meal Plan",
  "beef": "Beef",
  "boarding_statistics_version_b": "74% of users feel less stressed about planning & cooking meals since they've been using the meal plan.",
  "button_add_more_recipes": "Add more recipes",
  "button_add_to": "Add to...",
  "button_apply_for_this_week_mp": "Apply to this week only",
  "button_apply_to_saved_mp": "Apply to saved meal plan",
  "button_become_premium_kptn": "Become a Premium Kptn",
  "button_book_now": "Subscribe now",
  "button_continue": "CONTINUE",
  "button_discard": "Discard",
  "button_discover_premium": "Discover Premium",
  "button_discover_weekly_themes": "Discover Weekly Themes",
  "button_get_bonus_recipes": "Get 5 bonus recipes",
  "button_go_to_daily_recipes": "To the daily recipes",
  "button_go_to_mealplan_recipes": "To meal plan recipes",
  "button_more": "More",
  "button_no": "No 👎",
  "button_remove_mealplan": "Remove meal plan",
  "button_save_as_draft": "Save as draft",
  "button_see_more": "See more",
  "button_share_recipes": "Share recipes",
  "button_shop_all": "buy all",
  "button_start_trial_to_unlock": "Start free trial to unlock",
  "button_try_surprise_mealplan": "try surprise meal plan",
  "button_turn_on_notifications": "TURN ON NOTIFICATIONS",
  "button_undo": "Undo",
  "button_unlock_premium": "Unlock Premium",
  "button_unlock_premium_body_text": "Wanna get personalized recipes & access more features? Start your free trial!",
  "button_upgrade_to_premium": "Upgrade to premium",
  "button_view_product": "View product",
  "button_yes": "Yes 👍",
  "calories": "Calories",
  "campaign_header_ios": "Kitchen Hack",
  "cancel_anytime": "cancel anytime",
  "cart_dialog_invite_user_description": "People who join your list can add, edit, or delete products.",
  "cart_dialog_invite_user_title": "Invite a friend to your list.",
  "cart_invite_email_subject": "Invite to KptnCook “%@”",
  "change_day": "Change day",
  "clear_all": "Clear all",
  "coachmark_add_ingredients": "Add ingredients and find supermarkets near you",
  "coachmark_add_more_ingredients": "Add more items to the shopping list",
  "coachmark_add_to_collections": "Add recipe to your collections",
  "coachmark_cooked_existing_users": "New! Mark recipes as cooked and rate them",
  "coachmark_cooked_new_users": "Mark recipes as cooked and rate them",
  "coachmark_exchange_ingredients": "Tap the icon to replace ingredients",
  "coachmark_notes_existing_users": "For quick access, you can now find your notes here",
  "coachmark_notes_new_users": "Add a personal note to the recipe",
  "coachmark_recipes_personalised": "New: recipes tailored to your taste!",
  "coachmark_remove_recipe": "Swipe up to remove recipe from the shopping list",
  "coachmark_save_favorites": "Save the recipe in your favorites",
  "coachmark_select_multiple_recipes": "Select multiple recipes",
  "coachmark_share_mealplan": "Now you can share your meal plan with others",
  "coachmark_share_with_friends": "Share recipe with friends",
  "coachmark_shopping": "Tap on ingredient to add it to your shopping list",
  "coachmark_shopping_check_off_item": "Swipe left to check off item",
  "coachmark_shopping_delete_item": "Swipe right to delete item",
  "coachmark_swipe_right": "Swipe right to see weekly specials",
  "coachmark_swipe_up": "Swipe up or down to change between recipes",
  "collection_add_recipes": "Add recipes from favorites",
  "collection_add_to_collection": "Add to collection",
  "collection_added_popup": "Added to\\ncollection",
  "collection_create_new_collection": "Create a new collection",
  "collection_create_nextstepinfo": "In the next step you can add recipes to your collection",
  "collection_creating_collection": "Creating collection",
  "collection_delete_collection": "Delete collection",
  "collection_delete_dialog_text": "Do you want to delete this collection?",
  "collection_info_edit_later": "You can edit your collection later at any time.",
  "collection_new_collecion": "New collection",
  "collectiong_limit_reached_msg": "You have reached the maximum number of collections. Delete a collection to create a new one.",
  "collectiong_limit_reached_msg_body": "Delete a collection to create a new one",
  "collectiong_limit_reached_msg_title": "You have reached the maximum number of collections",
  "collections": "Collections",
  "collections_login_required": "You then have the possibility to create your own collections.",
  "cooked": "Cooked",
  "cooked_question": "Cooked?",
  "cooking_time": "%d min.",
  "cooking_time_with_preparation": "%d min. (+%d)",
  "daily_approxlabel": "2 Pers. ~",
  "day": "day",
  "deeplink_alert_title": "Oops!",
  "deeplink_error_message": "Something went wrong!",
  "diet_dairy_free_title": "Dairy Free",
  "diet_glutenfree_title": "Gluten Free",
  "discover_search_help_text": "What would you like to cook?",
  "discover_section1_title": "Recently viewed",
  "discover_section2_title": "Latest from the kitchen",
  "discover_section3_title": "Recommended for you",
  "discovery_list_favorites": "Get started with our favorites",
  "du_hast_bereits_einen_plan": "You already have a meal plan for that week. Would you like to replace it or add recipes to it?",
  "edit_mealplan": "Edit meal plan",
  "emojie_apple": "apple",
  "emojie_asian": "asian",
  "emojie_avocado": "avocado",
  "emojie_bacon": "bacon",
  "emojie_baguette": "baguette",
  "emojie_banana": "banana",
  "emojie_beef": "beef",
  "emojie_beer": "beer",
  "emojie_bowl": "bowl",
  "emojie_bread": "bread",
  "emojie_burger": "burger",
  "emojie_burrito": "burrito",
  "emojie_cake": "cake",
  "emojie_candy": "candy",
  "emojie_carrot": "carrot",
  "emojie_cheese": "cheese",
  "emojie_cherry": "cherry",
  "emojie_chestnut": "chestnut",
  "emojie_chicken": "chicken",
  "emojie_chili": "chili",
  "emojie_chocolate": "chocolate",
  "emojie_christmas": "Christmas",
  "emojie_cocktail": "cocktail",
  "emojie_coffee": "coffee",
  "emojie_cookie": "cookie",
  "emojie_corn": "corn",
  "emojie_crab": "crab",
  "emojie_croissant": "croissant",
  "emojie_cucumber": "cucumber",
  "emojie_curry_rice": "curry rice",
  "emojie_custard": "custard",
  "emojie_dango": "dango",
  "emojie_donut": "donut",
  "emojie_egg": "egg",
  "emojie_eggplant": "eggplant",
  "emojie_falafel": "falafel",
  "emojie_fish": "fish",
  "emojie_fish_cake": "fish cake",
  "emojie_fries": "French fries",
  "emojie_goat": "goat",
  "emojie_grape": "grapefruit",
  "emojie_honey": "honey",
  "emojie_hotdog": "hotdog",
  "emojie_kiwi": "kiwi",
  "emojie_lamb": "lamb",
  "emojie_lemon": "lemon",
  "emojie_meat": "meat",
  "emojie_melon": "melon",
  "emojie_milk": "milk",
  "emojie_mushroom": "mushroom",
  "emojie_noodles": "noodles",
  "emojie_octopus": "octopus",
  "emojie_oden": "oden",
  "emojie_onigiri": "onigiri",
  "emojie_orange": "orange",
  "emojie_paella": "paella",
  "emojie_pancake": "pancake",
  "emojie_peach": "peach",
  "emojie_peanut": "peanut",
  "emojie_pear": "pear",
  "emojie_pineapple": "pineapple",
  "emojie_pizza": "pizza",
  "emojie_popcorn": "popcorn",
  "emojie_pork": "pork",
  "emojie_potato": "potato",
  "emojie_pumpkin": "pumpkin",
  "emojie_rabbit": "rabbit",
  "emojie_rice": "rice",
  "emojie_rice_cracker": "rice cracker",
  "emojie_sake": "sake",
  "emojie_salad": "salad",
  "emojie_shrimp": "shrimp",
  "emojie_spicy": "spicy",
  "emojie_squid": "squid",
  "emojie_strawberry": "strawberry",
  "emojie_sushi": "sushi",
  "emojie_sweet_potato": "sweet potato",
  "emojie_taco": "taco",
  "emojie_tea": "tea",
  "emojie_tomato": "tomato",
  "emojie_turkey": "turkey",
  "emojie_wine": "wine",
  "empty_state_favorites_description": "Here you can collect your favorites from the changing daily recipes or discover recipes that match your diet in the meal plan.",
  "empty_state_favorites_title": "Your favorites list is still empty",
  "empty_state_shopping_list_description": "Tap the red plus at the bottom right or select the ingredients you need from the recipe detail view.",
  "emptystand_shortbreaklabel": "Short break.",
  "emptystand_shortbreaklabel2": "This week’s recipes are on their way. Please come back later.",
  "error_food_not_found_description": "Unfortunately, just a few recipes from our galley match your diet settings. Try changing your settings to find even more tasty recipes.",
  "error_food_not_found_title": "Error, food not found",
  "error_message_internet_overboard_description": "Whoops! We were unable to load your content. Please check your internet connection.",
  "fake_meal_plan": "Protein Powered Recipes for 7 Days",
  "favorite_action_cooked": "Cooked",
  "favorite_action_deletefromfavorites": "Remove from favorites",
  "favorite_action_deletefromlist": "Remove from list",
  "favorite_action_wantcook": "Want to cook",
  "favorite_hover_removed": "Recipe\\nremoved",
  "favorite_hoverview_added_text": "Added to collection",
  "favorite_label_cooked": "Cooked",
  "favorite_label_new": "New",
  "favorite_recently_deleted_infotext": "Accidentally deleted a recipe? We’ll keep it for you for 30 days.",
  "favorite_restore_button_text": "Restore",
  "favoritefiltermaincagtegory_title": "Category",
  "favoritefiltersorting_title": "Sort by",
  "favorites_add_button": "Add",
  "favorites_chooselist_label": "Choose a collection",
  "favorites_delete_button": "Delete",
  "favorites_deletefromlist_button": "Remove from list",
  "favorites_deletefromlist_button_short": "Remove from collection",
  "favorites_deleterecipefromlist_title": "Do you want to delete the recipe from this collection?",
  "favorites_deleterecipefromlistplural_title": "Do you want to delete the recipes from this collection?",
  "favorites_deleterecipeplural_title": "Do you want to delete these recipes?",
  "favorites_deleterecipesingular_title": "Do you want to delete this recipe?",
  "favorites_filter_random": "Random",
  "favorites_filter_reset": "Reset",
  "favorites_header_filterreset_button": "Reset Filter",
  "favorites_reshuffle_confirmation": "Shuffled recipes in random order",
  "favorites_select_recipes": "Select recipes",
  "favorites_shake_feature": "Psst! You can shake your phone to shuffle recipes",
  "favorites_title_filter": "Filter",
  "favoritesview_cell_morespace": "More favorite slots",
  "favoritesview_cooked_header_desc": "To add recipes from your favorites, press and hold down on the image or use the select button",
  "favoritesview_cooked_header_title": "Cooked",
  "favoritesview_emptystate_body": "Try another search term, or try changing your diet settings",
  "favoritesview_emptystate_title": "Oh snap! No recipes found",
  "favoritesview_history_header_desc": "Recently deleted",
  "favoritesview_label_cooked": "Cooked",
  "favoritesview_label_new": "New",
  "favoritesview_norecipesubtitlewithfavslotcount": "If you want to save more than 25 recipes, create a free account.",
  "favoritesview_norecipesubtitlewithfavslotcount_loggedin": "Your saved favorites will appear here.",
  "favoritesview_norecipetitle": "Collect your favorite recipes",
  "favoritesview_searchlabel": "Search for recipes or ingredients",
  "favoritesview_select_recipe": "Select recipe",
  "favoritesview_select_recipes": "Select recipes",
  "favoritesview_titlelabel": "My Favorites",
  "favoritesview_wantcook_header_desc": "To add recipes from your favorites, press and hold down on the image or use the select button",
  "favoritesview_wantcook_header_title": "Want to cook",
  "favpsaceinfo_loginbuttontext": "Login",
  "favspaceinfo_declinebuttontext": "Maybe later",
  "favspaceinfo_generalinfo_first": "From now on, you have unlimited favorite slots when you are logged in.",
  "favspaceinfo_popup": "You have almost reached the limit of %d recipe favorites. By creating a free account you get unlimited recipe space.",
  "favspaceinfo_popup_reached": "You have reached the limit of %d recipe favorites. By creating a free account you get unlimited recipe space.",
  "favspaceinfo_singleinfo": "By creating a free account we offer you unlimited space for your favorites.",
  "feature_coming_soon_description": "Soon this list will feature recipes curated just for you!",
  "feature_coming_soon_title": "Coming soon",
  "fish": "Fish",
  "flightmode_deactivate": "Deactivate",
  "flightmode_message": "Please deactivate the flight mode.",
  "flightmode_no_thanks": "No thanks",
  "flightmode_title": "Flight mode detected",
  "flipper_switch_daily": "Daily Recipes",
  "flipper_switch_weekly": "Weekly Special",
  "flipperviewcontroller_coachmark": "Swipe up to change between recipes",
  "flipperviewcontroller_coachmark_tablet": "Swipe right to change between recipes",
  "fragment_email_permission_required": "Email permission required",
  "game": "Game",
  "game_condition": "conditions of participation",
  "game_wirte_us": "Write us!",
  "general_cancel_button_text": "Cancel",
  "general_done_button_text": "Done",
  "general_edit_button_text": "Edit",
  "general_next_text": "Next",
  "general_no_button_text": "No",
  "general_ok_button_text": "OK",
  "general_oops": "Oops!",
  "general_or_text": "or",
  "general_save_button_text": "Save",
  "general_select_button_text": "Select",
  "general_yes_button_text": "Yes",
  "giveaway_title": "Giveaway",
  "got_it_button": "Got it",
  "hands_free_mode": "Hands-free mode",
  "have_account_log_in": "Already have an account? Log in.",
  "help_mail_signature_info_message": "For the developers",
  "help_mailaction_error_message": "We can't send your email, sorry!",
  "help_mailaction_subject": "Feedback for the Kptns",
  "help_maildelegate_success_message": "Your feedback was sent. Kptns will get back to you soon.",
  "help_maildelegate_success_title": "Success!",
  "how_to_cancel_subscription_description": "It's easy! Open the KptnCook app, go to your profile, tap on Settings in the top right corner, and then on \\\"Manage subscription\\\". You will be redirected to your subscriptions in the App Store, where you can select KptnCook. Then tap on \\\"Cancel subscription\\\" and \\\"Confirm\\\". All done!",
  "how_to_cancel_subscription_title": "How can I cancel?",
  "impressum_address": "KptnCook GmbH\\nMariendorfer Weg 64\\n12051 Berlin\\n+49 176 43655171\\nfeedback@kptncook.com\\n\\nResponsible for the content:\\nA. Reeg, E. Hoefer\\nRegistered at\\nAmtsgericht Charlottenburg, HRB 155002 B",
  "impressum_contact": "Contact",
  "impressum_copyright": "Copyright",
  "impressum_copyright_content": "The contents of the KptnCook app and the website www.kptncook.com is protected by copyright. For copyright reasons, the storage and reproduction of images or graphics from this app or website is prohibited for commercial purposes.",
  "info_and_ios": " and ",
  "info_contactlabel": "Imprint",
  "info_faqlabel": "FAQ",
  "info_feedbacklabel": "Feedback",
  "info_legal": "Legal",
  "info_logout": "Logout",
  "info_myaccountbutton": "My Profile",
  "info_privacylabel": "Privacy Policy",
  "info_privacylabel_onboarding": "Privacy Policy",
  "info_termslabel": "Terms of Use",
  "ingredient_status_not_exchangable": "Not \\nexchangeable",
  "ingredient_status_original": "original",
  "ingredientlistview_deselectallbuttontitle": "Deselect all",
  "ingredientlistview_selectallbuttontitle": "Select all",
  "ingredients": "Ingredients",
  "invalidaccesstoken_cancelbtntext": "Cancel",
  "invalidaccesstoken_loginbtntext": "Log in",
  "invalidaccesstoken_text": "You are not logged in.",
  "invalidaccesstoken_title": "Watch out, Kptn!",
  "kitchenhack_about_mealplan_description": "With KptnCook Premium, you can access all of our recipes & customize them to your liking — because your taste is one of a kind!",
  "kitchenhack_about_mealplan_title": "Looking for more?",
  "label_discount": "%@%% off",
  "label_premium": "PREMIUM",
  "label_special_offer": "Special Offer",
  "lamb": "Lamb",
  "likes": "Likes",
  "localNotification_reminder_message": "Create a meal plan from your favorites.",
  "localNotification_reminder_title": "New week, new plan!",
  "lockscreen_widget_no_meals": "No meals planned for today.",
  "login_error_text_invalid_email": "We couldn’t find your account. Is this the correct email address?",
  "login_error_text_invalid_password": "Invalid password. Please try again.",
  "login_loading": "Logging in",
  "meal planner_subs_button_cta_title_mail": "Start your 7-day free trial",
  "meal_plan": "Meal plan",
  "meal_plan_change_week": "Add recipes",
  "meal_plan_sharing_link_message": "Ahoy! Check out my KptnCook meal plan.",
  "meal_planner_choose_from_themes": "Choose a theme",
  "meal_planner_menu_button_change_theme": "Change weekly theme",
  "meal_planner_menu_button_delete_confirmation_title": "Do you really want to delete this meal plan?",
  "meal_planner_menu_button_delete_week": "Delete Meal Plan",
  "meal_planner_menu_button_duplicate_week": "Copy Meal Plan",
  "meal_planner_menu_button_duplicate_week_confimration_title": "Choose a week",
  "meal_planner_menu_button_duplicate_week_popup": "Your Meal Plan was created",
  "meal_planner_menu_button_duplicate_week_success": "Meal plan copied",
  "meal_planner_menu_button_fill_empty_days": "Fill empty days",
  "meal_planner_menu_button_refill_week": "Refill week",
  "meal_planner_menu_button_save_mealplan": "Save meal plan",
  "meal_planner_menu_button_switch_layout_cells": "Show grid view",
  "meal_planner_menu_button_switch_layout_list": "Show list view",
  "meal_planner_menu_create_screen_title": "Choose one of the options to create a meal plan.",
  "meal_planner_menu_create_screen_title_past_week": "You can't create a meal plan for past weeks.",
  "meal_planner_recipe_menu_button_add_to_shoppinglist": "Add to shopping list",
  "meal_planner_recipe_menu_button_buy_recipe": "Add to shopping list",
  "meal_planner_recipe_menu_button_change_day": "Change Day",
  "meal_planner_recipe_menu_button_delete_recipe": "Remove from meal plan",
  "meal_planner_recipe_menu_button_delete_recipe_confimration_title": "Do you really want to remove this recipe from your meal plan?",
  "meal_planner_recipe_menu_button_new_from_discovery": "New recipe from discovery",
  "meal_planner_recipe_menu_button_new_recipe": "Choose new recipe",
  "meal_planner_recipe_menu_button_new_recipe_from_favorites": "New recipe from favorites",
  "meal_planner_recipe_menu_button_new_surprise_recipe": "New surprise recipe",
  "meal_planner_select_from_favorites": "Choose from favorites",
  "meal_planner_select_random": "Add a surprise recipe",
  "mealpan_choose_title": "Choose a cover picture",
  "mealplan_combined_theme": "Theme Picks",
  "mealplan_confirm_and_create": "Confirm & create plan",
  "mealplan_deleted": "Meal plan deleted",
  "mealplan_diet_highprotein_description": "You eat a lot of proteins, few fats & carbohydrates.",
  "mealplan_diet_highprotein_title": "High protein",
  "mealplan_diet_keto_description": "You eat few carbs, but foods rich in fat.",
  "mealplan_diet_keto_title": "Keto",
  "mealplan_diet_lowcarb_description": "You eat lots of healthy proteins, and carbohydrates only in moderation.",
  "mealplan_diet_lowcarb_title": "Low carb",
  "mealplan_diet_meditter_description": "You eat a lot of veggies, seafood, nuts & olive oil.",
  "mealplan_diet_meditter_title": "Mediterranean",
  "mealplan_diet_omnivore_description": "You eat everything, meat and veggie products.",
  "mealplan_diet_omnivore_title": "Omnivore",
  "mealplan_diet_paleo_description": "You eat only fresh and unprocessed ingredients.",
  "mealplan_diet_paleo_title": "Paleo",
  "mealplan_diet_pescetarian_description": "You eat fish, but no meat.",
  "mealplan_diet_pescetarian_title": "Pescetarian",
  "mealplan_diet_vegan_description": "You don't eat any animal products.",
  "mealplan_diet_vegan_title": "Vegan",
  "mealplan_diet_vegetarian_description": "You don't eat meat or fish.",
  "mealplan_diet_vegetarian_title": "Vegetarian",
  "mealplan_editing_confirmation_apply_changes": "Apply changes",
  "mealplan_editing_confirmation_dont_apply_change": "Don't apply changes",
  "mealplan_editing_confirmation_question1": "You made some changes. Would you like to apply them to your saved meal plan or only for this week?",
  "mealplan_editing_confirmation_question2": "You made some changes. Would you like to apply them to your saved meal plan?",
  "mealplan_from_ingredients": "Meal plan from ingredients",
  "mealplan_popup_addedrecipe": "Added to Meal Plan",
  "mealplan_removed_confirmation": "Meal plan\\nremoved",
  "mealplan_removing_confirmation_question": "Do you really want to remove this plan from your saved meal plans?",
  "mealplan_replace": "Replace meal plan",
  "mealplan_saved": "Meal plan\\nsaved",
  "mealplan_select_days": "Select days",
  "mealplan_select_from_discovery": "Select recipe from discovery",
  "mealplan_select_week": "Select week",
  "mealplan_share": "Share meal plan",
  "mealplan_sharing_native": "Share KptnCook meal plan",
  "mealplan_subscription_bulletpoint1_a": "Unlock lots of new recipes that are just right for your specific diet",
  "mealplan_subscription_bulletpoint1_b": "Get hundreds of recipes tailored to you",
  "mealplan_subscription_bulletpoint1_c": "Less stress with easy meal planning",
  "mealplan_subscription_bulletpoint2_a": "Swap ingredients in the recipes according to your preferences.",
  "mealplan_subscription_bulletpoint2_c": "Try new recipes more often",
  "mealplan_subscription_bulletpoint3_a": "Save time and energy on your shopping and cooking",
  "mealplan_subscription_bulletpoint3_b": "Save time and energy on shopping",
  "mealplan_subscription_bulletpoint3_c": "Save time on shopping",
  "mealplan_subscription_buttontext_10_tage_kostenlos": "Start %@-day trial",
  "mealplan_subscription_description1": "Save time & energy with recipes & ingredients tailored to you.",
  "mealplan_subscription_description3": "Your subscription will start after %@ days if you have not canceled it beforehand.",
  "mealplan_subscription_note_24h_kuendbar": "Can be canceled up to 24 hours before end of trial period. Chargeable after %@ days. Debit will be made through Apple iTunes.",
  "mealplan_subscription_title_a": "Catch all the Premium benefits",
  "mealplan_subscription_title_b": "Enjoy all the Premium benefits",
  "mealplan_subscription_title_c": "Become a Premium Kptn & enjoy all the benefits",
  "mealplan_subscription_title_how_trial_works": "How the free trial works",
  "mealplan_sucsription_description2": "After %@ days you will receive a reminder that your trial subscription is ending soon.",
  "mealplan_theme_subtitle": "Pumpkin Season!",
  "mealplan_theme_title": "Our Best Pumpkin & Squash Recipes",
  "mealplan_weekly_special": "This week’s special",
  "mealplanner_add_to_shopping_list_navigationbar_title": "Shopping",
  "mealplanner_add_to_shopping_list_title": "Add to shopping list",
  "mealplanner_backend_404_message": "Unfortunately, something went wrong while validating your subscription. Try to access the meal plan again later. If you don't have access yet and you successfully completed your subscription, close and restart the app and attempt to restore purchases.",
  "mealplanner_backend_500_message": "Unfortunately, something went wrong while validating your subscription. Try to access the meal plan again later. If you don't have access yet, please contact the KptnCook support team at support@kptncook.com",
  "mealplanner_backend_502_message": "Unfortunately, something went wrong while validating your subscription. Try to access the meal plan again later. If you don't have access yet and you successfully completed your subscription, close and restart the app and attempt to restore purchases.",
  "mealplanner_backend_503_message": "We currently have problems with our system. Try to access the meal planner again later. If you still have problems, please contact the KptnCook support team at support@kptncook.com",
  "mealplanner_change_day_button": "CONFIRM SELECTION",
  "mealplanner_change_day_navigationbar_title": "Select day",
  "mealplanner_error_finish_purchase_title": "Please complete the purchase.",
  "mealplanner_error_internet_over_bord_title": "Internet overboard?",
  "mealplanner_error_ohno_title": "Oh no!",
  "mealplanner_error_okay": "Okay",
  "mealplanner_error_oops_title": "Oops!",
  "mealplanner_error_puchase_canceled_title": "Purchase transaction canceled",
  "mealplanner_error_sendmail": "Contact us",
  "mealplanner_favorite_week": "Favorites Week",
  "mealplanner_favorites_button_create_plan": "Create Meal Plan",
  "mealplanner_favorites_search_placeholder": "Search Favorites",
  "mealplanner_ingredients_last_searched": "Recent searches",
  "mealplanner_ingredients_popular_searches": "Popular searches",
  "mealplanner_ingredients_top_picks": "Top picks for you",
  "mealplanner_main_days_section_today": "Today",
  "mealplanner_main_next_week_label": "Next week",
  "mealplanner_main_this_week_label": "This week",
  "mealplanner_main_weekly_plan_title": "Meal Plan",
  "mealplanner_new_recipe_from_themes": "New recipe from themes",
  "mealplanner_not_recipe_found_error_message": "Sorry, we haven't found any recipes that match your food preference settings. We are working at full speed to add a variety of new recipes, so you'll have more meals to choose from in your galley soon!",
  "mealplanner_onboarding_favorites_button_description": "Plan your week with your favorite recipes.",
  "mealplanner_onboarding_favorites_button_title": "Choose from favorites",
  "mealplanner_onboarding_ingredients_button_description": "Got ingredients left over from last week? Turn them into a delicious meal!",
  "mealplanner_onboarding_ingredients_button_title": "Fridge Finds",
  "mealplanner_onboarding_ingredients_button_title_b": "Choose from ingredients",
  "mealplanner_onboarding_random_button_description": "We'll fill your week with recipes tailored to you and your preferences.",
  "mealplanner_onboarding_random_button_title": "Surprise me",
  "mealplanner_onboarding_saved_button_description": "Choose your favorite meal plan, and let the cooking begin!",
  "mealplanner_onboarding_saved_button_title": "Saved meal plans",
  "mealplanner_onboarding_theme_button_description": "Low carb, vegan, veggie — what do you feel like?",
  "mealplanner_onboarding_theme_button_title": "Choose a weekly theme",
  "mealplanner_rc_ineligibleerror": "The selected subscription offer is not available. Either you have already applied the offer before, or it is not available in your region.",
  "mealplanner_rc_insufficient_permission_error_message": "Please check if you are signed in on your device with a valid Apple ID that allows you to make in-app purchases. After that, you can try again.",
  "mealplanner_rc_invalid_app_user_id_message": "Something went wrong while sending your data. Please contact the KptnCook support team at support@kptncook.com.",
  "mealplanner_rc_invalid_credentials_message": "Something went wrong while processing your data. Please contact the KptnCook support team at support@kptncook.com.",
  "mealplanner_rc_invalid_receipt_message": "There was an issue validating your subscription. Please contact the KptnCook support team at support@kptncook.com.",
  "mealplanner_rc_invalidapplesubscriptionkeyerror": "Something went wrong while sending and validating your data. Please contact the KptnCook support team at support@kptncook.com.",
  "mealplanner_rc_invalidsubscriberattributeserror": "Something went wrong. Please contact the KptnCook support team at support@kptncook.com.",
  "mealplanner_rc_missing_receipt_file_message": "Please make sure you're logged in to the App Store with the account that you subscribed with. If you still can't access the meal plan, tap on Restore Purchases.",
  "mealplanner_rc_network_error_message": "Please check your internet connection and try again.",
  "mealplanner_rc_operation_already_in_progress_message": "Purchase is already in progress. In case you cannot access the meal planner yet, close and restart KptnCook and restore your purchases.",
  "mealplanner_rc_payment_pending_message": "You have a pending in-app purchase. To complete the purchase, please follow the instructions in your Apple account.",
  "mealplanner_rc_product_not_available_message": "The in-app purchase you are trying to make is not available for your device. Please choose a different package or contact the KptnCook support team at support@kptncook.com",
  "mealplanner_rc_productalreadypurchasederror": "Please make sure you're logged in to KptnCook with the account that you subscribed with. If you still can't access the meal plan, tap on Restore Purchases.",
  "mealplanner_rc_purchase_canceled_message": "You have not been charged. If you already have a subscription, please tap on Restore Purchases.",
  "mealplanner_rc_purchase_invalid_message": "Something went wrong with your subscription. Please contact the KptnCook support team at support@kptncook.com",
  "mealplanner_rc_purchase_not_allowed_message": "Please check if you are signed in on your device with a valid Apple ID and have the necessary permissions to make in-app purchases. After that, you can try again.",
  "mealplanner_rc_receipt_already_in_use_message": "If you can't access the meal plan, please make sure you're logged in to the App Store with the account that you subscribed with, and tap on Restore Purchases.",
  "mealplanner_rc_store_problem_message": "There was an issue validating your in-app purchase. If you already have a subscription, please tap Restore Purchases.",
  "mealplanner_rc_unexpected_backend_response_error_message": "There was an issue validating your in-app purchase. Please contact the KptnCook support team at support@kptncook.com",
  "mealplanner_rc_unknown_backend_error_message": "Sorry, there was an issue validating your in-app purchase. Please contact the KptnCook support team at support@kptncook.com.",
  "mealplanner_rc_unknown_error_message": "Sorry, there was an issue validating your in-app purchase. Please contact the KptnCook support team at support@kptncook.com.",
  "mealplanner_recommendations_button_description": "Get recipe suggestions based on your favorites.",
  "mealplanner_recommendations_button_title": "Recommendations for you",
  "mealplanner_search_for_ingredients": "Search for ingredients",
  "mealplanner_select_theme_title": "Select weekly theme",
  "mealplanner_subs_button_cta_second_line_mail": "We’ll remind you 2 days before it ends",
  "mealplanner_subscription_button_cta_first_line": "Try %@ for free",
  "mealplanner_subscription_button_cta_second_line": "Then",
  "mealplanner_subscription_button_restore_purchases": "Restore Purchases",
  "mealplanner_subscription_description": "Your subscription automatically renews unless you cancel at least 24 hours before current period ends. The payment is charged to your iTunes account. You can manage your subscription in your iPhone settings.",
  "mealplanner_subscription_entspricht": "corresponds to",
  "mealplanner_subscription_label_best_price": "Best Value",
  "mealplanner_subscription_label_bullet_1": "Discover new and delicious recipes",
  "mealplanner_subscription_label_bullet_2": "Get recipe suggestions that fit your diet",
  "mealplanner_subscription_label_bullet_3": "Save time on your weekly shopping",
  "mealplanner_subscription_label_savings_price": "%d%% DISCOUNT",
  "mealplanner_subscription_label_title": "Plan your week easily and without stress",
  "mealplanner_subscription_monthly": "Monthly subscription",
  "mealplanner_subscription_see_other": "See all plans",
  "mealplanner_subscription_subtitle_trialoptions": "Get our annual subscription at the best price or stay flexible with a monthly subscription.",
  "mealplanner_subscription_title_trialoptions": "Choose the subscription that suits you best",
  "mealplanner_subscription_yearly": "Annual subscription",
  "mealplanner_surprise_week": "Surprise Week",
  "media_permission_question_camera": "Please allow us to access your camera.",
  "media_permission_question_galery": "Please allow us to access your gallery.",
  "message_ingredient_not_exchangable": "This ingredient is a key component of the selected recipe and therefore cannot be substituted.",
  "modularisation_remove_ingredient": "Remove ingredient",
  "modularization_pop-up_bodytext1": "You can try this feature up to 5 times for free. Join Premium to change ingredients in even more recipes.",
  "modularization_pop-up_bodytext2": "You've swapped ingredients 5 times and used up the free trial. Join Premium to swap more ingredients!",
  "modularization_pop-up_title1": "You can still swap ingredients %d times",
  "modularization_pop-up_title2": "That was your last free ingredient swap",
  "month": "month",
  "mp_onboarding_button_not_now": "NOT NOW",
  "mp_onboarding_button_reminder_activate": "SET A REMINDER",
  "mp_onboarding_confirmation30_description": "Adjust the preferences in your Premium settings to get even more recipe inspiration.",
  "mp_onboarding_confirmation30_title": "Oops, we found less than 30 recipes!",
  "mp_onboarding_confirmation_button": "Got it!",
  "mp_onboarding_confirmation_description": "Do you want to give an ingredient a second chance or try out a new diet? You can always change your preferences in the settings.",
  "mp_onboarding_confirmation_title": "Adjust your selection at any time",
  "mp_onboarding_confirmation_updated_description": "You can always change your preferences in the Premium settings later.",
  "mp_onboarding_description_first_screen": "Low-carb, vegan or maybe keto? No matter what your eating habits are, the meal planner helps you find the best recipes for every diet.",
  "mp_onboarding_description_first_screen_b": "The majority of our users say they feel less stressed since they've been planning meals with KptnCook Premium.",
  "mp_onboarding_description_second_screen": "Allergies, intolerances, or you can't stand cilantro? No problemo! Your meal planner will only show you recipes with ingredients you really eat!",
  "mp_onboarding_description_second_screen_b": "89% of our users say they've been cooking with more variety since they have access to over 3,000 recipes in KptnCook Premium.",
  "mp_onboarding_description_third_screen": "By planning ahead, you save both time and resources – because you only buy what you actually need.",
  "mp_onboarding_description_third_screen_b": "With KtpnCook Premium, 63% of our users save time on shopping, since you can get everything you need for the week with just one shopping trip.",
  "mp_onboarding_diet_confirmation_title": "Your diet",
  "mp_onboarding_diet_subtitle_highprotein": "High protein? It's high time!",
  "mp_onboarding_diet_subtitle_keto": "Keto — taking low-carb to the next level!",
  "mp_onboarding_diet_subtitle_lowcarb": "Low-carb: Goodbye carbs, hello energy boost!",
  "mp_onboarding_diet_subtitle_lowfat": "Stay fit with lean meals!",
  "mp_onboarding_diet_subtitle_paleo": "Paleo – Stone Age dinner for winners!",
  "mp_onboarding_diet_tagging_explanation": "We mark the %@ daily & weekly recipes with a tag, so they're easier to spot.",
  "mp_onboarding_diet_tagging_explanation_copy": "We mark the",
  "mp_onboarding_diet_tagging_explanation_copy_copy": "daily & weekly recipes with a tag, so they're easier to spot.",
  "mp_onboarding_final_description": "In the Premium section, you'll find lots of delicious recipes tailored to your preferences!",
  "mp_onboarding_final_title": "Done!",
  "mp_onboarding_reminder_description": "When life gets busy, it's best to plan your week in advance. That way you'll always stay on top of things.",
  "mp_onboarding_reminder_timer_explanation": "3 days before the week starts should be enough to start planning meals.",
  "mp_onboarding_reminderpage_title": "When would you like to plan your week?",
  "mp_onboarding_title_begin_button": "LET'S GET STARTED",
  "mp_onboarding_title_first_screen": "Get personalized recipes with our meal plan",
  "mp_onboarding_title_first_screen_a": "Food is a matter of taste! That's why with KptnCook Premium you get recipes that are tailored to you and your specific diet.",
  "mp_onboarding_title_first_screen_b": "74% feel less stressed about cooking",
  "mp_onboarding_title_second_screen": "Leave out ingredients you don’t eat",
  "mp_onboarding_title_second_screen_b": "89% try new recipes more often",
  "mp_onboarding_title_third_screen": "Keep calm and plan your week ahead",
  "mp_onboarding_title_third_screen_b": "63% save time on shopping",
  "network_error_button_retry": "Try again",
  "network_error_message": "Whoops, there was an error. Please try again later.",
  "network_error_title": "Internet overboard?",
  "new_recipe_from_favourites": "New recipe from favorites",
  "note_price_gurantee": "The accuracy of the information cannot be guaranteed. Some prices might be outdated.",
  "notes_alerttext": "Your personal notes will be synchronized on all your devices.",
  "notes_alerttitle": "Become a real Kptn and create an account",
  "notes_cancelbutton": "Cancel",
  "notes_donebutton": "Done",
  "notes_edit": "Create",
  "notes_later_button": "Later",
  "notes_login_button": "Sign up",
  "notes_notetextview_placeholder": "Add a private note for this recipe.",
  "notes_show": "Show",
  "notes_titlelabel": "My notes",
  "notification_permission_confirm": "Okay",
  "notification_permission_decline": "Another time",
  "notification_permission_description": "Allow KptnCook to send you push notifications to inform you about tasty recipes.",
  "notification_permission_title": "Get notified!",
  "ns_camera_usage_description": "Please allow access to your camera so that you can take a profile picture.",
  "ns_location_always_usage_description": "Please allow access to your location so that we can show stores near you.",
  "ns_location_when-in_use_usage_description": "Please allow access to your location so that we can show stores near you.",
  "ns_microphone_usage_description": "Please allow access to your microphone so that you can add audio to your bug reports.",
  "ns_photo_library_usage_description": "Please allow access to your gallery so that you can pick a profile picture.",
  "offer_ends": "Offer ends in:",
  "onboarding_almost_there_screen_bulletpoint1": "Finding recipes for your diet",
  "onboarding_almost_there_screen_bulletpoint2": "Sorting out ingredients you don’t eat",
  "onboarding_almost_there_screen_bulletpoint3": "Personalizing your recipes",
  "onboarding_button_test_for_7_days": "Start your free 7-day trial",
  "onboarding_description_healthy_eating": "In addition to the 3 daily recipes, with our premium meal planner you'll discover many more recipes tailored to your food preferences.",
  "onboarding_existinguser_description": "If you don’t eat meat and fish we will only show you vegetarian and vegan daily recipes from now on.",
  "onboarding_existinguser_title": "Ahoy Kptn, we have great news!",
  "onboarding_finalscreen_title_new": "Try out the meal planner for 7 days free of charge!",
  "onboarding_goal1": "Learn how to cook",
  "onboarding_goal2": "Eat healthier",
  "onboarding_goal3": "Enjoy cooking together",
  "onboarding_goal4": "Cook at home more often",
  "onboarding_goal5": "Reduce stress in the kitchen",
  "onboarding_goal6": "Get inspired by new recipes",
  "onboarding_goal7": "Save money",
  "onboarding_goal8": "Other",
  "onboarding_goals_subtitle": "Choose up to three options.",
  "onboarding_goals_title": "What brings you to KptnCook?",
  "onboarding_label_free_version": "Included in the free version",
  "onboarding_premiumscreen_description_a": "More variety & less stress",
  "onboarding_premiumscreen_description_b": "Join Premium and enjoy a varied diet with recipes and ingredients tailored to your preferences!",
  "onboarding_premiumscreen_title_a": "With KptnCook Premium at the helm, you stay fit and save energy with recipes just the way you like them!",
  "onboarding_premiumscreen_title_b": "Kick back & eat healthy with KptnCook Premium",
  "onboarding_servings_screen_subtitle": "You can change your serving count at any time.",
  "onboarding_servings_screen_title": "How many servings do you usually cook?",
  "onboarding_settings_i_eat_everything": "I eat everything",
  "onboarding_shoppinglist_description_1": "From now on you will be able to shop for multiple recipes.",
  "onboarding_shoppinglist_description_2": "Simply select the ingredients that you need and add them to the shopping list.",
  "onboarding_shoppinglist_description_3": "You’ll now find the retailer selection in the shopping list.",
  "onboarding_shoppinglist_title1": "Shopping List Deluxe!",
  "onboarding_shoppinglist_title2": "Select the ingredients",
  "onboarding_shoppinglist_title3": "Off to the supermarket",
  "onboarding_slidebuttontitle_last": "Got it",
  "onboarding_slidebuttontitle_next": "Next",
  "onboarding_statistics_version_a": "70% of users now have a more balanced diet and healthier lifestyle using the meal planner.",
  "onboarding_step1_button1": "Continue",
  "onboarding_step1_description": "At KptnCook you'll get 3 easy and healthy recipes every 24 hours.\\nHave fun cooking!",
  "onboarding_step1_description_24h_recipes": "Discover 3 new recipes for free every day, or get an extra helping of inspiration with KptnCook Premium.",
  "onboarding_step1_description_new": "Get inspired by 3 delicious daily recipes in the free version, or discover even more meals tailored to you in the premium meal planner!",
  "onboarding_step1_privacy": "By continuing, I agree to KptnCook’s Terms of Use\\nand Privacy Policy.",
  "onboarding_step1_privacy_link": "Privacy Policy",
  "onboarding_step1_title": "Ahoy Captain! Quick & healthy recipes in sight!",
  "onboarding_step2_button1": "Got it",
  "onboarding_step2_description": "Our daily recipes are available for 24 hours. Every day you can discover 3 new and easy recipe ideas.",
  "onboarding_step2_description_new": "You'll get 3 healthy & simple recipes every day in the free version of the app.",
  "onboarding_step2_title": "Discover 3 new recipes every day.",
  "onboarding_step2_title_new": "Which daily recipes would you like to see?",
  "onboarding_step3_button2": "Vegetarian",
  "onboarding_step3_description": "If you don’t eat meat and fish we will only show you vegetarian and vegan daily recipes.",
  "onboarding_step3_title": "Which kind of recipes interest you?",
  "onboarding_step3_title_new": "With our premium meal plan, you can access personalized recipe recommendations & enjoy a more varied diet!",
  "onboarding_step4_button1": "Discover recipes",
  "onboarding_step4_button2": "Maybe later",
  "onboarding_step4_description": "Save time, reduce stress, and discover more delicious recipes with our meal planner.",
  "onboarding_step4_description_health": "Save time, reduce stress, and discover more delicious recipes with our meal planner.",
  "onboarding_step4_description_new": "Our meal plan helps you eat healthier, more balanced meals. You can also exclude the foods you don't eat!",
  "onboarding_step4_description_time": "No problem! Save time, reduce stress, and discover more delicious recipes with your personal meal plan!",
  "onboarding_step4_title": "Your meal planning made easy",
  "onboarding_step4_title_health": "Healthy eating\\nmade easy!",
  "onboarding_step4_title_new": "71% eat healthier",
  "onboarding_step4_title_time": "No time for\\nshopping & cooking?",
  "onboarding_step5_description_new": "With our meal planner, you can plan grocery shopping and meals for the entire week, which saves you time and stress.",
  "onboarding_subtitle2_choose_diets": "Choose between 9 different diets & leave out ingredients you don’t eat.",
  "onboarding_subtitle2_discover_recipes": "Discover 3 new recipes every day & collect all your favorites — for free!",
  "onboarding_subtitle3_search_recipes": "Use up leftover ingredients with our ‘Fridge Finds’ feature.",
  "onboarding_subtitle4_save_time": "Eat healthier while saving time and money",
  "onboarding_title1_recipes_in_sight": "Ahoy Captain! Quick & healthy recipes ahead!",
  "onboarding_title2_personalized_recipes": "Get personalized recipes",
  "onboarding_title3_fridge_finds": "Find recipes based on ingredients",
  "onboarding_title4_personalized_mealplan": "Create meal plans",
  "onboarding_title_almost_there": "You’re almost there!",
  "onboarding_title_healthy_eating": "Enjoy healthy meals without the stress — with the meal plan!",
  "onboarding_whats_your_diet_description": "If you choose \\\"vegetarian\\\", we will only show you vegetarian and vegan daily & weekly recipes.",
  "onboarding_whats_your_diet_title": "What kind of recipes do you want to see?",
  "online_ordering_button": "Continue to Rewe",
  "online_ordering_dialog_msg": "You can check all items before you complete your order. Have fun shopping :)",
  "online_ordering_dialog_title": "We will now redirect you to the Rewe online shop",
  "password_reset_loading": "Resetting password",
  "per_month_ios": "per month",
  "plan_empty_state_button1": "I want to plan",
  "plan_empty_state_button2": "Plan for me",
  "plan_empty_state_description": "Sit back and let us fill your meal plan for you, or add any recipes you like.",
  "plan_empty_state_title": "Fill your week with delicious meals",
  "planning_choose_from_discovery": "Choose recipes from discovery",
  "planning_choose_from_favorites": "Choose recipes from favorites",
  "play_store": "Google Play Store",
  "pop_up_description_share_recipes": "Do you like your new recipes? Then why not share them with your friends!",
  "popular_search": "Popular searches",
  "popup_added_to_favorites": "Added to favorites",
  "popup_go_back_to_discard_mealplan": "If you go back now, your meal plan will be discarded.",
  "popup_surprise_recommendations_description": "Ahoy, Kptn! The recipes in the ‘Surprise me’ option are now based on your personal taste. Try the new & improved surprise feature!",
  "popup_surprise_recommendations_title": "New! Recipe recommendations",
  "pork": "Pork",
  "poultry": "Poultry",
  "premium_log_in_message": "Already a Premium member? Log in",
  "privacy_policy_dialog_message": "We’ve made it easier for you to understand which data we collect and process to continuously improve KptnCook for you. The updated terms and privacy policy are effective immediately. By clicking okay, you agree to our updated terms of use and privacy policy. If you have any questions, write to support@kptncook.com",
  "privacy_policy_dialog_title": "We’ve updated our terms and privacy policy",
  "profile_button_password": "Change password",
  "profile_button_peronal": "Change name",
  "profile_changeemaiinfo": "To change your email address, please enter your password. Then, confirm your new email address.",
  "profile_changeemail": "Change email address",
  "profile_changeimage_choose": "Pick from gallery",
  "profile_changeimage_skip": "Skip",
  "profile_changeimage_takepicture": "Take picture",
  "profile_changeimage_title": "Change profile image",
  "profile_changename": "Change name",
  "profile_changename_success": "Your details have been changed successfully.",
  "profile_changepassword_loading": "Changing password",
  "profile_changepassword_success": "Your password has been changed successfully.",
  "profile_changepasword": "Change password",
  "profile_confirmemail": "Be a real Kptn and confirm your email address.",
  "profile_confirmnow_text": "Confirm now",
  "profile_cookedlabel": "Cooked",
  "profile_currentpasword": "Current password",
  "profile_dashboard_cooking_history": "Cooking history",
  "profile_dashboard_description_text": "Reduce the stress of cooking last minute and enjoy the perks of personalized meal plans.👨‍🍳",
  "profile_dashboard_profiletext_1": "Ahoy Kptn %@,",
  "profile_dashboard_profiletext_2": "good to see you!",
  "profile_dashboard_progress_0": "Go for it, Kptn! 🤗",
  "profile_dashboard_progress_0_20": "Keep it up, you're doing great! 💪",
  "profile_dashboard_progress_100": "You cooked all of your favorite recipes. You're one hell of a chef! 🥳",
  "profile_dashboard_progress_21_40": "Way to go! You're nearly halfway there! 👍",
  "profile_dashboard_progress_41_60": "Keep going! Lots of tasty recipes left to try! 🙌",
  "profile_dashboard_progress_61_80": "You're the real Kptn in your kitchen! 😊",
  "profile_dashboard_progress_81_99": "Let's get it! You're almost there! 👏",
  "profile_dashboard_statstext": "You have cooked %d out of your %d favorite recipes.",
  "profile_delete_account_button": "Send email",
  "profile_delete_account_message": "We will send an email to %@ with a link to permanently delete your account. If you have a premium subscription, it will remain active. You can manage your subscription in your settings at any time.",
  "profile_delete_account_title": "Delete account?",
  "profile_deleteaccount": "Delete account",
  "profile_edit_email_confirm_msg": "Your data has been changed. Please confirm your email address.",
  "profile_email_sent_ok": "Awesome! Your email was successfully sent.",
  "profile_logout_dialog_msg": "To have access to your data, you have to log in again.",
  "profile_logout_dialog_title": "Are you sure you want to log out?",
  "profile_maybalater_text": "Maybe later",
  "profile_newpassword": "New password",
  "profile_savechanges": "Save changes",
  "profile_settings_accountsettings": "My account",
  "profile_settings_banner_subtitle1": "Save unlimited recipes",
  "profile_settings_banner_subtitle2": "Edit shopping lists together",
  "profile_settings_banner_subtitle3": "Backup your favorites & collections",
  "profile_settings_banner_title": "Create a free account now",
  "profile_settings_email": "E-Mail",
  "profile_settings_name": "Name",
  "profile_settings_password": "Password",
  "profile_settings_title": "Edit account",
  "profile_temperature": "Temperature",
  "promocode_accountdesclabel": "Be a real Kptn and sign up to save your favorite recipes permanently in your account.",
  "promocode_codedesclabel_success": "Your favorites list has grown! New recipes have been added.",
  "promocode_failurealert_message": "Something went wrong. But a real Kptn never gives up! Let's try again.",
  "promocode_isusedalert_message": "You already used this code, Kptn.",
  "promocode_loginbutton": "Sign up now",
  "promocode_sharecodebutton": "Share recipes",
  "promocode_sharemessage": "Ahoy Kptn! An amazing surprise is waiting for you, activate the code now!",
  "promocode_successtitle": "Hip hip hurray!",
  "push_consent_screen_description": "Keep up with our latest daily recipes, new features, and amazing discounts for KptnCook Premium.",
  "push_consent_screen_title": "Don’t miss out!",
  "quote1_date_of_review": "6/19/22",
  "quote1_description": "This app is amazing!!! I subscribed to the meal plan and I have NO REGRETS. My LIFE IS REVOLUTIONIZED. It has made me feel a lot healthier all with tasty recipes. I definitely recommend this app to anyone who needs that push towards a healthier lifestyle.",
  "quote1_platform_of_review": "App Store",
  "quote1_user_name": "RoyalGhostSquid",
  "quote2_date_of_review": "5/11/22",
  "quote2_description": "It is an amazing app! I can’t recommend it enough!!! It has recipes with pictures for every step which makes it even easy for my children to follow (and they are still young). We enjoy the app as a family and love that it prepares a neat shopping list too! Makes shopping so much more enjoyable!",
  "quote2_platform_of_review": "App Store",
  "quote2_user_name": "E. B. W.",
  "quote3_date_of_review": "5/8/22",
  "quote3_description": "Best cooking app ever. Every step is described in detail and very easy to follow. Lots of different options for specific diets too (like vegetarian, vegan...)",
  "quote3_platform_of_review": "Google Play Store",
  "quote3_user_name": "Becca",
  "quote4_date": "08.06.2022",
  "quote4_description": "\\\"Great app: varied and super tasty recipes with great pictures explained very clearly.\\\"",
  "quote4_user_name": "Ulla Franck",
  "rate": "Rate",
  "rated": "Rated",
  "rating_cancelbutton": "No thanks",
  "rating_message": "If you like cooking with us, please rate the KptnCook app.",
  "rating_ratebutton": "Rate now",
  "rating_remindbutton": "Remind me later",
  "rating_title": "Do you love us?",
  "recentlyadded": "Recently added",
  "recipe_custom_title": "Others",
  "recipe_detail_add_to_cart_button": "Add to shopping list",
  "recipe_detail_drink_header": "Goes well with",
  "recipe_detail_order_online_button": "Order ingredients online",
  "recipe_feature_drinkfriday": "Drink Friday",
  "recipe_feature_sweetsunday": "Sweet Sunday",
  "recipe_ratings_popup_description1": "Would you cook this again?",
  "recipe_ratings_popup_description2": "%@%% would cook it again",
  "recipe_ratings_popup_description4": "Only %@%% would cook it again",
  "recipe_ratings_popup_marked_as_cooked": "Marked as cooked ✅",
  "recipe_ratings_popup_title1": "Well done, Kptn! 👏",
  "recipe_ratings_popup_title2": "Other Kptns agree!",
  "recipe_ratings_popup_title3": "Don't send this recipe over the plank yet!",
  "recipe_ratings_popup_title4": "Recipes are a matter of taste",
  "recipe_ratings_popup_title5": "Shiver me timbers!",
  "recipe_tinder_amount_of": "%d of %d",
  "recipe_tinder_end_of_rating_message": "Done! All recipes marked with a thumbs-up have been added to your favorites!",
  "recipe_tinder_subtitle1": "The recipes you like will be added to your favorites.",
  "recipe_tinder_title1": "Do these recipes sound delicious?",
  "recipe_tinder_title1_b": "Which recipes would you cook?",
  "recipedetail_fat": "Fat",
  "recipedetails_activate_cookingmode": "Start cooking!",
  "recipedetails_author_kptntitle": "Recipe by",
  "recipedetails_author_kptntitle_ios": "Kptn",
  "recipedetails_button_favorite": "Favorite",
  "recipedetails_button_share": "Share",
  "recipedetails_calories": "Cal",
  "recipedetails_carbohydrate": "Carb",
  "recipedetails_favoritehint": "Did you know you can add recipes to your favorites list?",
  "recipedetails_ingredients_loading": "Loading ingredients",
  "recipedetails_instructionsbutton": "View steps",
  "recipedetails_linkbuttonblog": "VISIT FOOD BLOG",
  "recipedetails_linkbuttonwebsite": "Visit Website",
  "recipedetails_neareststoretitle": "NEAREST STORE",
  "recipedetails_nutritionsubtitlelabel": "per serving (approx.)",
  "recipedetails_nutritiontitlelabel": "NUTRITION FACTS",
  "recipedetails_protein": "Protein",
  "recipedetails_sharinghint": "Did you know you can share recipes with your friends?",
  "recipedetails_shopping_coachmark_ingredient": "Select ingredients and add them to the shopping list.",
  "recipedetails_shopping_coachmark_stores": "Here you can find your shopping list and nearest grocery stores.",
  "recipedetails_tiptitle": "TIP",
  "recipesteps_enjoy_drink_title": "Cheers!",
  "recipesteps_enjoytitle": "Time to dig in!",
  "recipesteps_footer_cookedbutton_active": "Cooked",
  "recipesteps_footer_cookedbutton_inactive": "Mark as cooked",
  "recipesteps_footer_sharelabel": "Share recipe",
  "recipesteps_readytitle": "Ready",
  "recipesteps_title": "Step %1$@ of %2$@",
  "registration_avatar_add": "Add",
  "registration_optional_title": "Optional",
  "reminder_notification_text": "Create your weekly meal plan from your favorite recipes and save time, money & stress!",
  "reminder_notification_title": "It's time to plan your meals for the week",
  "removed_from_mealplan": "Removed from meal plan",
  "retailer_ordering_message_rewe": "Order your ingredients online and get them conveniently delivered to your home.",
  "review_message": "Now that you're back on board, please write us a review in the AppStore. You'll not only help us, but also future Kptns!",
  "save_fifty_percent": "50% discount",
  "saved_changes_confirmation": "Changes saved",
  "saved_mealplans_emptyscreen_description": "Just select or create a meal plan, select ‘save meal plan’ from the top menu, and it will be saved here.",
  "saved_mealplans_emptyscreen_title": "Has a meal plan won you over?",
  "saved_mealplans_header": "Saved meal plans",
  "seafood": "Seafood",
  "search": "Search",
  "search_empty_result_body": "Try another search term.",
  "segment_off": "Off",
  "segment_on": "On",
  "settings_choose_country_title": "Choose region",
  "settings_choose_language_title": "Select Language",
  "settings_country_label": "Region",
  "settings_diet_all": "Everything",
  "settings_diet_title": "Diet",
  "settings_diet_veggie": "Vegetarian",
  "settings_effects_snow": "Snow effect",
  "settings_header_app_settings": "Basic Settings",
  "settings_header_legal": "Legal notices",
  "settings_header_newsletter": "Newsletter",
  "settings_header_support": "Support",
  "settings_language": "Language",
  "settings_language_searchbar_placeholder": "Search Language",
  "settings_mealplan_diet": "Meal Plan - Your Diet",
  "settings_mealplan_dietscreen_description": "With the meal plan, you have a wider selection of dietary preferences to choose from than in the daily recipes.",
  "settings_mealplan_do_not_eat": "I don't eat that",
  "settings_mealplan_do_not_eat_description": "If you have allergies, intolerances or just don't like a certain ingredient, let us know.",
  "settings_mealplan_options": "Premium settings",
  "settings_mealplan_reminder": "Reminder",
  "settings_measurement_label": "Measurements",
  "settings_newsletter_desc": "I would like to be informed about new recipes, tips and food news.",
  "settings_portion_label": "Servings",
  "settings_region_searchbar_placeholder": "Search region",
  "settings_shuffle_effect": "Shake & Shuffle",
  "settings_shuffle_effect_decription": "Sort your favorites randomly",
  "settings_subscription": "Subscription",
  "settings_subscription_manage": "Manage subscription",
  "settings_subscription_upgrade": "Upgrade to Pro",
  "settings_temperature": "Temperature unit",
  "settings_title": "Settings",
  "share_clipb": "Clipboard",
  "share_clipboard": "Copied to clipboard",
  "share_content": "Look at this great recipe I've just discovered in the KptnCook app.",
  "share_content_meta": "Get the recipe now in the KptnCook app!",
  "share_other": "Other",
  "share_promocode_meta": "Activate your promo code in the KptnCook app!",
  "shared_mealplan_subscribe_to_save": "Subscribe to copy & save this meal plan",
  "shared_mealplan_subscribe_to_save_highlighted_part": "Subscribe",
  "shared_mealplan_subscribed_subtitle": "Copy this meal plan to save it.",
  "shared_mealplan_subscribed_subtitle_highlighted_part": "Copy this meal plan",
  "shared_mealplan_subscribed_title": "Shared meal plan",
  "shopping_add_friend": "Add a friend",
  "shopping_adjust_items": "Adjust items",
  "shopping_basicingredient_sectiontitle": "You might have this at home",
  "shopping_choose_a_color": "Choose a color",
  "shopping_choose_shopping_list": "Choose a shopping list",
  "shopping_coachmark_check": "Swipe left to check off",
  "shopping_completionview_bottombuttontext": "Later",
  "shopping_completionview_info": "Would you like to clear your shopping list?",
  "shopping_completionview_title": "Done",
  "shopping_completionview_upperbuttontext": "Clear list",
  "shopping_create_list": "Create list",
  "shopping_create_shopping_list": "Create shopping list",
  "shopping_delete_list": "Delete list",
  "shopping_delete_list_question": "Do you want to delete this shopping list?",
  "shopping_edit_title": "Edit list",
  "shopping_empty_state_button": "Create shopping list",
  "shopping_empty_state_subtitle": "You can share your shopping list with friends and edit it together.",
  "shopping_empty_state_title": "Create your first shopping list",
  "shopping_footer_totalstring": "Total",
  "shopping_headercell_deactivefilterinfo": "Please deactivate the filter to continue. Just tap on the recipe picture.",
  "shopping_headercell_deleterecipequestion": "Would you like to delete this recipe from the shopping list?",
  "shopping_headercell_gotorecipebutton": "Go to recipe",
  "shopping_leave_list": "Leave list",
  "shopping_leave_list_question": "Do you want to exit this shopping list?",
  "shopping_limit_reached_msg": "Delete one of your lists to create a new one.",
  "shopping_limit_reached_title": "You have reached the maximum number of shopping lists",
  "shopping_login_msg": "Once signed up, you can share this shopping list with your friends.",
  "shopping_login_title": "Come aboard and discover more advantages",
  "shopping_members": "Members",
  "shopping_navbartitletext": "Shopping",
  "shopping_navbartitletext_selected": "%d selected",
  "shopping_ok": "Okay",
  "shopping_owner": "Owner",
  "shopping_recipe_deletebuttontext": "Delete",
  "shopping_regularingredient_sectiontitle": "You need",
  "shopping_retailerview_productpossiblynotavailableinfo": "Ingredients with this symbol might not be available at your store.",
  "shopping_sharing_description": "Join the shopping list '%@'.",
  "shopping_sharing_text": "I'd like to share the shopping list '%@' with you. Just click the link:",
  "shopping_sharing_title": "Shop with KptnCook",
  "shopping_sign_up": "Sign up",
  "shopping_synchronization_msg": "Create an account so you can edit your shopping list together with other Kptns.",
  "shopping_tableview_emptymessagebottom": "Add items by selecting ingredients in the recipe overview or by using the \\\"add\\\" button",
  "shopping_tableview_emptymessagetop": "Start filling up your shopping list",
  "shopping_tableview_itemcell_basic_noproductstring": "No price available",
  "shopping_tableview_itemcell_noproductstring": "No product available",
  "shopping_tableview_sectionheader_hideitemsbutton": "Hide checked off items",
  "shopping_tableview_sectionheader_showitemsbutton": "Show checked off items",
  "shopping_updated_amoment": "A moment ago",
  "shopping_updated_text": "List from %@",
  "shopping_you_are_the_owner": "You are the owner",
  "signup_button_continue": "Get started",
  "signup_button_register_with_email": "Register with e-mail",
  "signup_confirm_message": "I am at least 16 years old and accept KptnCook’s Terms of Use and Privacy Policy.",
  "signup_description_create_account": "Create a free account to store unlimited recipes and access them from anywhere.",
  "signup_description_email_confirmation": "We'll send you an email in which you can confirm your registration.",
  "signup_description_your_name": "Your name only appears in your profile. It's not visible to others.",
  "signup_email": "Email",
  "signup_email_invalid": "Email address is not valid",
  "signup_email_mandatory": "Email address*",
  "signup_first_name": "First name*",
  "signup_firstname": "First Name",
  "signup_forgotpassword_message": "No problem! We will send an email link to reset your password.",
  "signup_last_name": "Last name*",
  "signup_lastname": "Last Name",
  "signup_loginsuccess_title": "Welcome!",
  "signup_name_too_short": "Name is too short",
  "signup_newsletter_labeltext": "I would like to be informed about new recipes, tips and food news.",
  "signup_nice_too_see_you": "Great to see you again!",
  "signup_or_continue_with": "Or continue with",
  "signup_password": "Password",
  "signup_password_too_short": "Password is too short",
  "signup_passworderror_message": "We couldn't find your account. Did you send us the right email address?",
  "signup_passwordsuccess_message": "We have sent an email to %@. Click the link to reset your password.",
  "signup_passwordsuccess_title": "Reset password",
  "signup_screen_apple": "Continue with Apple",
  "signup_screen_description": "You need an account to use your personal meal plan and save your settings.",
  "signup_screen_description2": "After you tell us your name, we'll send you an email in which you can confirm your registration.",
  "signup_screen_email": "E-mail*",
  "signup_screen_facebook": "Continue with Facebook",
  "signup_screen_google": "Continue with Google",
  "signup_screen_name": "First name*",
  "signup_screen_password": "Password*",
  "signup_screen_question_login": "Already have an account? Log in",
  "signup_screen_surname": "Last name*",
  "signup_screen_title": "Create an account & start planning",
  "signup_screen_title2": "Ahoy, Kptn!\\nWelcome on board",
  "signup_sign_in_here": "Already have an account? Log in here.",
  "signup_signuperror_message": "We couldn't create an account. Please try again later.",
  "signup_skip": "Skip",
  "signup_submitbutton_login": "Log in",
  "signup_submitbutton_reset": "Reset password",
  "signup_subscribe_to_newsletter": "I'd like to receive more recipes & food tips in my inbox!",
  "signup_switchbutton_password": "Forgot password?",
  "signup_title_create_save_passsword": "Create a \\nsecure password",
  "signup_title_name": "What's your name?",
  "signup_title_sign_up_options": "How would you like to register?",
  "signup_title_welcomeback": "Welcome back on board!",
  "signup_title_your_email": "What's your email address?",
  "signup_with_google": "Sign in with Google",
  "singup_account_exists": "An account for this email address already exists",
  "singup_add_email_to_reset_password": "We will send a link to your email address to reset your password.",
  "singup_add_profile_picture": "Add a profile picture.",
  "singup_continue": "Next",
  "singup_create_account": "Create account",
  "singup_create_password": "Create a password",
  "singup_email": "Email address",
  "singup_email_question": "What’s your email address?",
  "singup_forgot_password": "Forgot your password?",
  "singup_loading": "Signing up",
  "singup_login_answer_close": "Close",
  "singup_login_answer_login": "Log in",
  "singup_login_question": "Would you like to log in?",
  "singup_mail_for_you": "Check your inbox!",
  "singup_name_question": "Ahoy! What’s your name?",
  "singup_ok": "Okay",
  "singup_password_too_short": "Your password must be at least 6 characters long.",
  "singup_resend_email": "Send email again",
  "singup_reset_password": "RESET PASSWORD",
  "singup_stepx": "Step %d/%d",
  "singup_welcome_on_board": "Great to have you on board! Please confirm your email address to complete registration.",
  "singup_with_facebook": "Continue with Facebook",
  "siri_command1_part2": "“Hey Siri, previous KptnCook step!”",
  "siri_command1_part3": "to see the previous step",
  "siri_command2_part2": "“Hey Siri, mark KptnCook recipe as cooked!”",
  "siri_command2_part3": "to mark recipe as cooked",
  "siri_command3_part2": "“Hey Siri, next KptnCook step!”",
  "siri_command3_part3": "to see the next step",
  "siri_commands_part1": "Say",
  "siri_go_to_next_step": "Next step",
  "siri_go_to_previous_step": "previous step",
  "siri_mark_cooked": "Mark recipe as cooked",
  "snackbar_mealplanner_shoppinglist": "You can’t add more than 10 recipes to the shopping list.",
  "sponsored": "sponsored",
  "status_label_ingredients_adjusted": "ingredients adjusted",
  "status_label_step_omitted": "step omitted",
  "stepcontent_enjoyimagename": "StepsFinalEN",
  "steps_cooked_feedback_dialog_text": "Hooray! You have cooked this recipe %d x.",
  "steps_cooked_feedback_text": "You've cooked this recipe %d x. Keep it up! 👏",
  "store_openingtime": "%1$@-%2$@",
  "storelocation_getdirectionsbutton": "Get direction",
  "storelocation_primer_description_2": "In order to see the nearest stores & opening hours, please activate the location access for KptnCook in your iPhone settings.",
  "storelocation_primer_no_button_1_ios": "DON'T\\nALLOW",
  "storelocation_primer_no_button_2": "MAYBE\\nLATER",
  "storelocation_primer_ok_button_1": "ALLOW",
  "storelocation_primer_ok_button_2": "OPEN\\nSETTINGS",
  "storelocation_primer_title_2": "Find your local grocery stores",
  "storelocation_primerdescription_1_ios": "In order to see the nearest stores & opening hours, please allow KptnCook to use your location.",
  "storelocation_primertitle_1": "Find your local grocery stores",
  "storelocation_storeclosed": "Closed",
  "storelocation_storelocationnotactivatedmessage": "Please activate location-based service.",
  "subscription_bullets_title": "Your benefits with Premium",
  "subscription_comparison_table_text1": "3 new daily recipes",
  "subscription_comparison_table_text10": "Get recipe recommendations",
  "subscription_comparison_table_text2": "Save & share unlimited recipes",
  "subscription_comparison_table_text3": "Adjust number of servings",
  "subscription_comparison_table_text4": "Create and share shopping lists",
  "subscription_comparison_table_text5": "Choose from 9 dietary plans",
  "subscription_comparison_table_text6": "Exclude ingredients",
  "subscription_comparison_table_text7": "Find recipes with ingredients you have at home",
  "subscription_comparison_table_text8": "Create customized meal plans",
  "subscription_comparison_table_text9": "Choose from 14+ weekly themes",
  "subscription_screen_features": "Features",
  "subscription_screen_free": "Free",
  "subscription_screen_legal_note2": "You can cancel the subscription in your settings up to 24 hours before the end of the term. After that, the subscription is automatically renewed and subject to a charge. The subscription will be debited by iTunes. You can only try out the Premium plan one time for 7 days free of charge. If you have already used the trial, the selected monthly or annual subscription will be automatically activated. In order to use the meal plan, you need an account, which you can create in the next step.",
  "subscription_screen_premium": "Premium",
  "subscription_screen_timeline_text1": "Become a Premium Kptn & enjoy all the benefits",
  "subscription_screen_timeline_text2": "After 5 days, you will receive a reminder that your trial will end soon.",
  "subscription_screen_timeline_text3": "Your subscription will start after 7 days if you have not canceled it during the trial.",
  "subscription_screen_timeline_title1": "Today",
  "subscription_screen_timeline_title2": "Day 5",
  "subscription_screen_timeline_title3": "Day 7",
  "sunbscription_screen_per_week": "%@/ week, cancel anytime",
  "surprise_me_from_my_favorites": "Surprise recipes from your favorites",
  "surprise_me_with_new_recipes": "Surprise recipes picked especially for you",
  "survey_result_text": "Thank you for your opinion. And here are the votes:",
  "tabbar_favorites_title": "Favorites",
  "tabbar_mealplanner_title": "Meal Plan",
  "tabbar_planning_title": "Planning",
  "tabbar_profile_title": "Profile",
  "tabbar_recipe_title": "Recipes",
  "tabbar_shopping_title": "Shopping",
  "tabbar_today_title": "Today",
  "tag_swappable_ingredients": "Swappable Ingredients",
  "timer_done": "Done",
  "timer_min": "min.",
  "timer_notification_background_message": "Your timer for %@ just ended.",
  "timer_notification_background_title": "Timer done.",
  "timer_notification_popup_part1": "Ahoy! \\nYour timer for ",
  "timer_notification_popup_part2": " just ended",
  "timer_notitification_pop_withouttitle": "Ahoy! \\nYour timer just ended.",
  "timer_sec": "sec.",
  "timer_start": "Start",
  "timer_stop": "Stop",
  "timer_title": "Set timer",
  "tracking_popup": "This helps us improve the performance of our app and personalize the app content for you.",
  "trial_screen_title1_b": "Got ingredients left over? Find matching recipes!",
  "trial_screen_title2_b": "Discover over 14 recipe themes",
  "trial_screen_title3_b": "Create & personalize your meal plans",
  "try_again": "Try again",
  "update_steps_error_message": "Whoops! There was a problem updating the recipe step, please close and reopen app to try again.",
  "user_not_found": "We could not find the account. Please try again.",
  "user_same_id": "An account with that email already exists.",
  "user_wrong_credentials": "Invalid email or password. Please try again.",
  "vegan": "Vegan",
  "veggie": "Vegetarian",
  "watch_favorite_button_title": "Add to favorites",
  "week": "week",
  "week_day_friday": "Friday",
  "week_day_monday": "Monday",
  "week_day_saturday": "Saturday",
  "week_day_sunday": "Sunday",
  "week_day_thursday": "Thursday",
  "week_day_tuesday": "Tuesday",
  "week_day_wednesday": "Wednesday",
  "weeklyview_titlelable": "Weekly Special",
  "whats_new_button_title": "Got it",
  "whats_new_item_1_subtitle": "Have recipes displayed on your lock screen.",
  "whats_new_item_1_title": "Widget with recipe preview",
  "whats_new_item_2_subtitle": "Now you can scroll to the next step in hands-free mode.",
  "whats_new_item_2_title": "Cook with Siri",
  "whats_new_message_text1": "Discover recipes tailored to your leftover ingredients!",
  "whats_new_message_text2": "Save your favorite meal plans as templates and enjoy them again and again!",
  "whats_new_message_text3": "Rate the recipes you've cooked and let us know if you liked them!",
  "whats_new_message_text4": "Now the \\\"Surprise Me\\\" meal plan is tailored to your preferences!",
  "whats_new_message_title1": "Meal Plan from Ingredients",
  "whats_new_message_title2": "Save meal plans",
  "whats_new_message_title3": "Rate recipes",
  "whats_new_message_title4": "Custom recipe recommendations",
  "whats_new_title": "Updates for iOS 16",
  "widget_description": "Quickly access our newest recipes.",
  "widget_title": "Daily recipes",
  "year": "Year"
};
